#!/usr/bin/env bash
# daft-gpu — Red Daft OS GPU compatibility manager.
#
# Detects AMD/NVIDIA hardware, activates the matching stack, or falls back
# to software rendering/compute so every GL/Vulkan/OpenCL app still runs on
# GPU-less machines. Designed to be boring: sysfs-only detection, no deps
# beyond coreutils; lspci/clinfo are used when present, never required.
#
# Usage:
#   daft-gpu detect          print detected GPUs (machine-readable lines)
#   daft-gpu status          human-readable capability summary
#   daft-gpu activate-auto   detect + activate (used by daft-gpu.service)
#   daft-gpu activate amd|nvidia|fallback   force a mode
set -uo pipefail

PROFILE_D=/etc/profile.d/daft-gpu.sh

log() { echo "[daft-gpu] $*"; }

# ── Detection (sysfs-only) ─────────────────────────────────────────────
# Emits lines: "<vendor> <pci_addr> <device_id>"
detect() {
  local dev class vendor
  for dev in /sys/bus/pci/devices/*; do
    [[ -r "$dev/class" ]] || continue
    class="0x$(cat "$dev/class" 2>/dev/null)"
    case "$class" in
      0x0300*|0x0302*) ;;          # VGA compatible / 3D controller
      *) continue ;;
    esac
    vendor="$(cat "$dev/vendor" 2>/dev/null)"
    case "$vendor" in
      0x1002) echo "amd ${dev##*/} $(cat "$dev/device" 2>/dev/null)" ;;
      0x10de) echo "nvidia ${dev##*/} $(cat "$dev/device" 2>/dev/null)" ;;
    esac
  done
}

have_amd()    { detect | grep -q '^amd' ; }
have_nvidia() { detect | grep -q '^nvidia' ; }

load_modules() {
  for m in "$@"; do
    modprobe "$m" 2>/dev/null && log "loaded $m" || log "module not available: $m"
  done
}

write_profile() {
  cat > "$PROFILE_D" <<EOF
# Generated by daft-gpu ($(date -u +%FT%TZ)) — mode: $1
EOF
  case "$1" in
    amd)
      if [[ -d /opt/rocm ]]; then
        cat >> "$PROFILE_D" <<'EOF'
export PATH="/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH"
export LD_LIBRARY_PATH="/opt/rocm/lib:${LD_LIBRARY_PATH:-}"
export ROCM_PATH=/opt/rocm
EOF
      fi
      ;;
    nvidia)
      if ls -d /usr/local/cuda-* >/dev/null 2>&1 || [[ -d /usr/local/cuda ]]; then
        cat >> "$PROFILE_D" <<'EOF'
export PATH="/usr/local/cuda/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}"
export CUDA_HOME=/usr/local/cuda
EOF
      fi
      ;;
    fallback)
      cat >> "$PROFILE_D" <<'EOF'
# No discrete GPU detected: force software paths so apps still run.
export GALLIUM_DRIVER=llvmpipe
export LIBGL_ALWAYS_SOFTWARE=1
EOF
      ;;
  esac
  chmod 644 "$PROFILE_D"
}

activate_amd() {
  log "activating AMD stack"
  load_modules amdgpu
  # KFD char device appears once amdgpu+HSA_AMD are up (/dev/kfd).
  [[ -e /dev/kfd ]] && log "/dev/kfd present — ROCm compute ready" \
                     || log "/dev/kfd absent — install rocm-runtime .daft + check firmware"
  write_profile amd
}

activate_nvidia() {
  log "activating NVIDIA stack"
  load_modules nvidia nvidia_uvm nvidia_drm
  # GSP-firmware cards (Turing+): modeset enables modern DRM client caps.
  [[ -d /sys/module/nvidia_drm ]] && \
    [[ -r /sys/module/nvidia_drm/parameters/modeset ]] && \
      echo Y > /sys/module/nvidia_drm/parameters/modeset 2>/dev/null || true
  write_profile nvidia
}

activate_fallback() {
  log "no discrete GPU — activating software fallback (llvmpipe/lavapipe/PoCL)"
  write_profile fallback
}

activate_auto() {
  if have_nvidia; then activate_nvidia
  elif have_amd; then activate_amd
  else activate_fallback
  fi
}

status() {
  echo "== Red Daft GPU status =="
  local gpus; gpus="$(detect)"
  if [[ -n "$gpus" ]]; then
    echo "$gpus"
  else
    echo "no discrete GPU detected (software fallback active)"
  fi
  echo "-- kernel modules --"
  for m in amdgpu radeon nouveau nvidia nvidia_uvm; do
    [[ -d "/sys/module/$m" ]] && echo "  loaded: $m"
  done
  [[ -e /dev/kfd     ]] && echo "  device: /dev/kfd (ROCm/KFD)"
  [[ -e /dev/nvidiactl ]] && echo "  device: /dev/nvidiactl"
  echo "-- compute stacks --"
  ls -d /opt/rocm* >/dev/null 2>&1 && echo "  ROCm: $(ls -d /opt/rocm* | tr '\n' ' ')" || true
  ls -d /usr/local/cuda* >/dev/null 2>&1 && echo "  CUDA: $(ls -d /usr/local/cuda* | tr '\n' ' ')" || true
  echo "-- software backends --"
  command -v clinfo     >/dev/null && echo "  OpenCL CPU: pocl (run 'clinfo')"
  ls /usr/share/vulkan/icd.d/*lvp* >/dev/null 2>&1 && echo "  Vulkan SW: lavapipe"
  echo "-- compat score --"
  if command -v daft-compat >/dev/null; then daft-compat / ; else echo "  (daft-compat not installed)"; fi
}

case "${1:-status}" in
  detect)        detect ;;
  status)        status ;;
  activate-auto) activate_auto ;;
  activate)      case "${2:-}" in
                   amd) activate_amd ;; nvidia) activate_nvidia ;;
                   fallback) activate_fallback ;;
                   *) echo "usage: daft-gpu activate amd|nvidia|fallback" >&2; exit 2 ;;
                 esac ;;
  *) echo "usage: daft-gpu {detect|status|activate-auto|activate amd|nvidia|fallback}" >&2
     exit 2 ;;
esac
